version: '3.8'

services:
  backend:
    build: ./FullServer
    container_name: campfire-backend
    ports:
      - "3412:5000"
    env_file:
      - path: ./FullServer/.env
        optional: true
      - path: stack.env
        optional: true
    environment:
      NODE_ENV: production
    restart: unless-stopped
